version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: music_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=music
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./db-data:/var/lib/postgresql/data