services:
  db:
    image: postgres:16-alpine
    container_name: music_postgres
    env_file: .env.db
    ports:
      - '5432:5432'
    volumes:
      - ./db-data:/var/lib/postgresql/data
    healthcheck:
      test:
        ['CMD-SHELL', 'pg_isready -U "$${POSTGRES_USER}" -d "$${POSTGRES_DB}"']
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    container_name: music_api
    env_file: .env
    environment:
      - NEST_LOG_LEVEL=debug
      - CSV_FILE=/app/data/Song_list.csv
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '3001:3000'
    volumes:
      - ./data:/app/data:ro

volumes:
  db-data:
