version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: music_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 25

  tal-music:
    image: tal-music:latest
    container_name: tal_music_app
    depends_on:
      db:
        condition: service_healthy
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - PORT=3000
      - NODE_ENV=dev
      - JWT_SECRET=superlongrandomsecret
      - JWT_EXPIRES=86400
    volumes:
      - ./data:/app/data
    command: >
      sh -c "
        until nc -z db 5432; do echo '⏳ waiting for db...'; sleep 1; done;
        node dist/migrate.js || true;
        node dist/main.js
      "
